name = "MC Endless Oddities"
author = "Mr.Bones / KrononC"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16a77d654e69991168e00e4556499632c9750acf1f2bde7c0f5813066d3b4a40"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
