name = "MC Endless Oddities"
author = "Mr.Bones / KrononC"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1987f7e156c395893e94f9da63eabf26e6f3046e01adc9cbc035ee0fa9bee73d"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
