name = "MC Endless Oddities"
author = "Mr.Bones / KrononC"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc9793848a891d376432ac402c1ae8ad24d427222605917c356a241babfd9ef"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
