name = "Apple Trees Revived [Forge & Fabric][1.12.x - 1.17.1]"
filename = "AppleTreesRev-Fabric-1.17.1-v2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3503/790/AppleTreesRev-Fabric-1.17.1-v2.6.jar"
hash-format = "murmur2"
hash = "2286358046"

[update]
[update.curseforge]
file-id = 3503790
project-id = 452033
release-channel = "beta"
