name = "Apple Trees Revived [Forge & Fabric][1.12.x - 1.17.1]"
filename = "AppleTreesRev-Fabric-1.17.1-v2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/522/AppleTreesRev-Fabric-1.17.1-v2.5.jar"
hash-format = "murmur2"
hash = "2148054935"

[update]
[update.curseforge]
file-id = 3478522
project-id = 452033
release-channel = "beta"
