name = "Artifality"
filename = "artifality-mc1.17.1-0.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3492/69/artifality-mc1.17.1-0.4.2.jar"
hash-format = "murmur2"
hash = "990464579"

[update]
[update.curseforge]
file-id = 3492069
project-id = 490812
release-channel = "beta"
