name = "Chat+"
filename = "chatplus-1.17.1-2.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3427/462/chatplus-1.17.1-2.1.5.jar"
hash-format = "murmur2"
hash = "3427575933"

[update]
[update.curseforge]
file-id = 3427462
project-id = 437174
release-channel = "beta"
