name = "Cull Leaves"
filename = "cullleaves-2.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3470/922/cullleaves-2.3.0.jar"
hash-format = "murmur2"
hash = "2271474664"

[update]
[update.curseforge]
file-id = 3470922
project-id = 423254
release-channel = "beta"
