name = "Cull Leaves"
filename = "cullleaves-2.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/538/cullleaves-2.3.1.jar"
hash-format = "murmur2"
hash = "2210244944"

[update]
[update.curseforge]
file-id = 3496538
project-id = 423254
release-channel = "beta"
