name = "Enderscape"
filename = "enderscape-0.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/466/enderscape-0.1.0.jar"
hash-format = "murmur2"
hash = "1000129659"

[update]
[update.curseforge]
file-id = 3490466
project-id = 536638
release-channel = "beta"
