name = "Enderscape"
filename = "enderscape-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/451/enderscape-0.1.1.jar"
hash-format = "murmur2"
hash = "3965345648"

[update]
[update.curseforge]
file-id = 3495451
project-id = 536638
release-channel = "beta"
