name = "Happiness (is a) Warm Gun"
filename = "HWGMod-1.17-1.0.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/604/HWGMod-1.17-1.0.20.jar"
hash-format = "murmur2"
hash = "4203622475"

[update]
[update.curseforge]
file-id = 3478604
project-id = 448106
release-channel = "beta"
