name = "Hydrogen"
filename = "hydrogen-fabric-mc1.17.1-0.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AZomiSrC/versions/mc1.17.1-0.3.1/hydrogen-fabric-mc1.17.1-0.3.jar"
hash-format = "sha512"
hash = "db4079c26bf27b38d32ae60a47e7d347e01d43def5987e5c2cb25218e427b2f10f7fcb36f9de5d486a0953637793cd90450f8d2d7ff1a31cf8a90af3794646ad"

[update]
[update.modrinth]
mod-id = "AZomiSrC"
version = "gqJWYgtD"
