name = "Indium"
filename = "indium-1.0.0+mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3484/852/indium-1.0.0+mc1.17.1.jar"
hash-format = "murmur2"
hash = "191940847"

[update]
[update.curseforge]
file-id = 3484852
project-id = 459496
release-channel = "beta"
