name = "Iris Shaders"
filename = "iris-and-sodium-mc1.17-1.1.2+build.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3451/773/iris-and-sodium-mc1.17-1.1.2+build.9.jar"
hash-format = "murmur2"
hash = "2018118617"

[update]
[update.curseforge]
file-id = 3451773
project-id = 455508
release-channel = "beta"
