name = "MC Dungeons Artifacts"
filename = "mcdar-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/827/mcdar-1.4.1.jar"
hash-format = "murmur2"
hash = "3562878143"

[update]
[update.curseforge]
file-id = 3399827
project-id = 476788
release-channel = "beta"
