name = "MCDoom"
filename = "MCDoom-Fabric-1.17-4.0.30.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/193/MCDoom-Fabric-1.17-4.0.30.jar"
hash-format = "murmur2"
hash = "891728604"

[update]
[update.curseforge]
file-id = 3504193
project-id = 368765
release-channel = "beta"
