name = "MCDoom"
filename = "MCDoom-Fabric-1.17-4.0.28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/881/MCDoom-Fabric-1.17-4.0.28.jar"
hash-format = "murmur2"
hash = "4257390396"

[update]
[update.curseforge]
file-id = 3495881
project-id = 368765
release-channel = "beta"
