name = "Space Dimensions (Fabric)"
filename = "agape_space_17-0.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3497/762/agape_space_17-0.3.3.jar"
hash-format = "murmur2"
hash = "1767733192"

[update]
[update.curseforge]
file-id = 3497762
project-id = 429841
release-channel = "beta"
