name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.7.3-newconfig.3+mc1.17.1-pre1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/244/mousewheelie-1.7.3-newconfig.3+mc1.17.1-pre1.jar"
hash-format = "murmur2"
hash = "4204196731"

[update]
[update.curseforge]
file-id = 3434244
project-id = 317514
release-channel = "beta"
