name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.7.0+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3491/766/notenoughcrashes-3.7.0+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "93411339"

[update]
[update.curseforge]
file-id = 3491766
project-id = 353890
release-channel = "beta"
