name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3480/453/sodium-extra-mc1.17.1-0.3.5.jar"
hash-format = "murmur2"
hash = "3924701839"

[update]
[update.curseforge]
file-id = 3480453
project-id = 447673
release-channel = "beta"
