name = "When Dungeons Arise - Fabric!"
filename = "DungeonsArise-1.17.1-2.1.48-fabric-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/114/DungeonsArise-1.17.1-2.1.48-fabric-beta.jar"
hash-format = "murmur2"
hash = "617563128"

[update]
[update.curseforge]
file-id = 3467114
project-id = 511812
release-channel = "beta"
