name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.14.0_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/275/Xaeros_Minimap_21.14.0_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "4173495381"

[update]
[update.curseforge]
file-id = 3396275
project-id = 263420
release-channel = "beta"
